<?php

/**
 * @file
 * Install and uninstall functions for the Tin Can API (Content Types) module.
 */

/**
 * Implements hook_install().
 */
function tincanapi_media_install() {
  $media_tracking_types = array(
    'youtube',
    'vimeo',
  );
  variable_set('tincanapi_media_tracking_types', $media_tracking_types);
}

/**
 * Implements hook_uninstall().
 */
function tincanapi_media_uninstall() {
  variable_del('tincanapi_media_tracking_types');
}

